# Generated by Django 5.0.1 on 2024-01-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_processing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StoredImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="uploads/")),
                ("identifier", models.CharField(max_length=50, unique=True)),
                ("path", models.CharField(max_length=255)),
            ],
        ),
    ]
