# Generated by Django 5.0.1 on 2024-01-07 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_processing", "0003_delete_image_storedimage_uploaded_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="FrontendEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
