# Generated by Django 5.0.1 on 2024-01-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_processing", "0005_alter_storedimage_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storedimage",
            name="image",
            field=models.ImageField(upload_to="uploads/"),
        ),
    ]
