# Generated by Django 5.0.1 on 2024-01-13 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("image_processing", "0006_alter_storedimage_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="storedimage",
            name="format",
            field=models.CharField(default="JPG", max_length=255),
            preserve_default=False,
        ),
    ]
